name: My first scriptworkflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Run Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh