name: MyFirstWorkflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "My first github job"

            - name: listfiles
              run: ls
              
            - name: Readfile
              run: cat README.md  